# Site settings
title: Cancer Research UK: Mail preferences
email: chris.platts@cancer.org.uk
description: >
	Cancer Research UK mail preferences - example pages.
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  crukorg

# Build settings
markdown: kramdown
